In [15]:
import torch
import numpy as np

source = 'hello'
target = 'olleh'
unique_characters = set(source + target)
character_size = len(unique_characters)
hidden_size = 2
num_layers = 1
learning_rate=0.1
print('Unique chars:',unique_characters)

Unique chars: {'l', 'e', 'o', 'h'}


In [ ]:
char2index = {c: i for i, c in enumerate(unique_characters)}
index2char = {i: c for i, c in enumerate(unique_characters)}
def one_hot_encoding(sentence, vocabulary_size):
    """Simple utility to convert characters into one hot encoding"""
    one_hot = np.zeros((1, len(sentence), vocabulary_size))
    for index, c in enumerate(sentence):
        one_hot[0, index, char2index[c]] = 1
    return one_hot

### Simple Preprocessing 
We simply convert each character to a number 

In [21]:
source_one_hot = one_hot_encoding(source, character_size)
target_indexed = [char2idx[c] for c in target]
print('Source one hot encoded:\n',source_one_hot)
print('target index:\n',target_indexed)
source_v = torch.FloatTensor(source_one_hot)
target_v = torch.LongTensor(target_indexed)

Source one hot encoded:
 [[[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]]]
target index:
 [2, 0, 0, 1, 3]


In [22]:
rnn = torch.nn.RNN(input_size=len(uniq_char), hidden_size=len(uniq_char), num_layers=1, batch_first=True)
optimizer = torch.optim.Adam(rnn.parameters(), lr=learning_rate)

for epoc in range(10):
    optimizer.zero_grad()
    out, hidden = rnn(source_v)
    loss = torch.nn.functional.cross_entropy(out.squeeze(0), target_v)
    word_indexes = out.argmax(dim=2).data.numpy()[0]
    loss.backward()
    optimizer.step()
    predicted_word = ''.join([idx2chr[i] for i in word_indexes])
    print('Predicted word:', predicted_word)
    print('Epoc:', epoc, ' loss:', loss.item())

Predicted word: hollh
Epoc: 0  loss: 1.3083043098449707
Predicted word: hllhh
Epoc: 1  loss: 1.2409477233886719
Predicted word: llllh
Epoc: 2  loss: 1.1034144163131714
Predicted word: olllh
Epoc: 3  loss: 1.0143383741378784
Predicted word: olllh
Epoc: 4  loss: 0.9636384844779968
Predicted word: olllh
Epoc: 5  loss: 0.8992897272109985
Predicted word: olllh
Epoc: 6  loss: 0.8313344717025757
Predicted word: olllh
Epoc: 7  loss: 0.7630955576896667
Predicted word: olllh
Epoc: 8  loss: 0.6958886981010437
Predicted word: olleh
Epoc: 9  loss: 0.6376038789749146
